### ISSUE TITLE
how to fix “Error loading stacks: An error occurred while serving your request.“”？

### ISSUE THREAD

**Issue by mswinner** [exceptionless/Exceptionless#1071]
When this happens，exceptionless is down   ，then i just delete  deployment  pvc（elasticsearch data）  ，and reinstall deployment

k8s  env。

**Comment by niemyjski** [comment]
What is the error you are getting in the api pod logs as well as from the response?

**Comment by mswinner** [comment]
<img width="907" alt="fc2636e3d5e8aac2129f1a0f08a43ff" src="https://user-images.githubusercontent.com/13105601/161930576-3887e6b9-ec6e-4100-8def-6f3b0a02b5e0.png">

**Comment by mswinner** [comment]
[400] POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true

---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

--- End of inner exception stack trace ---

at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.CountAsync(IRepositoryQuery query, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticReadOnlyRepositoryBase.cs:line 429

at Exceptionless.Web.Controllers.EventController.GetInternalAsync(AppFilter sf, TimeInfo ti, String filter, String sort, String mode, Int32 page, Int32 limit, String after, Boolean usesPremiumFeatures) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 293

at Exceptionless.Web.Controllers.EventController.GetAsync(String filter, String sort, String time, String offset, String mode, Int32 page, Int32 limit, String after) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 205

at lambda_method311(Closure , Object )

at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

[10:32:30 ERR] traceID=ca96e7bf9245c26bcd9fe45c0aa90b21 HTTP GET /api/v2/events?filter=(status:open+OR+status:regressed)&limit=15&mode=stack_new&offset=480m&time=last+week responded 500 in 50.6162 ms

[10:32:30 ERR] traceID=ca96e7bf9245c26bcd9fe45c0aa90b21 HTTP GET /api/v2/events?filter=(status:open+OR+status:regressed)&limit=15&mode=stack_new&offset=480m&time=last+week responded 500 in 50.9866 ms

[10:32:30 ERR] Unhandled error: Error getting document count

Original: [ElasticsearchClientException] Request failed to execute. Call: Status code 400 from: POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

Server Error (Index=): all shards failed

[400] POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true

Foundatio.Repositories.Exceptions.DocumentException: Error getting document count

Original: [ElasticsearchClientException] Request failed to execute. Call: Status code 400 from: POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

Server Error (Index=): all shards failed

[400] POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true

---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /prod-events-2022.04.03%2Cprod-events-2022.04.04%2Cprod-events-2022.04.05%2Cprod-events-2022.04.06/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

--- End of inner exception stack trace ---

at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.CountAsync(IRepositoryQuery query, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticReadOnlyRepositoryBase.cs:line 429

at Exceptionless.Web.Controllers.EventController.GetInternalAsync(AppFilter sf, TimeInfo ti, String filter, String sort, String mode, Int32 page, Int32 limit, String after, Boolean usesPremiumFeatures) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 293

at Exceptionless.Web.Controllers.EventController.GetAsync(String filter, String sort, String time, String offset, String mode, Int32 page, Int32 limit, String after) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 205

at lambda_method311(Closure , Object )

at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

[10:32:30 ERR] traceID=3d1f97d9f390b2aaf6c51e00f7cf9953 HTTP GET /api/v2/events?filter=(status:open+OR+status:regressed)&limit=15&mode=stack_users&offset=480m&time=last+week responded 500 in 48.1937 ms

[10:32:30 ERR] traceID=3d1f97d9f390b2aaf6c51e00f7cf9953 HTTP GET /api/v2/events?filter=(status:open+OR+status:regressed)&limit=15&mode=stack_users&offset=480m&time=last+week responded 500 in 48.5581 ms

**Comment by mswinner** [comment]
i use  elasticsearch cluster   ,wait for some minutes ，“Error loading stacks: An error occurred while serving your request.“ again！  wow~！

**Comment by niemyjski** [comment]
Can you please attach the index mappings for the stack_id field for the following indices: prod-events-2022.04.03, prod-events-2022.04.04,prod-events-2022.04.05,prod-events-2022.04.06. Here is docs on how to get it: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-field-mapping.html It's saying stack_id isn't a keyword field but it should be.

**Comment by mswinner** [comment]
![image](https://user-images.githubusercontent.com/13105601/162122666-441f7ca5-4dc7-429c-a677-c1e344be3277.png)

![image](https://user-images.githubusercontent.com/13105601/162122756-fd13c729-c3e3-4a55-a7ca-c2aeee5ab43c.png)

![image](https://user-images.githubusercontent.com/13105601/162122806-5ebbde52-bda4-4035-a18b-c8ab2ed6afc0.png)

why??   install  over minutes！

**Comment by mswinner** [comment]
[container-bmyfgq.log](https://github.com/exceptionless/Exceptionless/files/8439773/container-bmyfgq.log)

**Comment by mswinner** [comment]
help me！ thanks

**Comment by niemyjski** [comment]
Hello,

Please provide the logs requested in the previous reply. Also please note additional configuration (to turn off mapping size elastic plugin) will be required as outlined in the self-hosting guide when using your own Elasticsearch image. We recommend using our Elasticsearch image if possible.

**Comment by ShajithJ** [comment]
Hi.

Facing the same issue here "Error loading stacks", on using our own Elasticsearch installed as a package.

Could you explain a bit more about the addition configuration, you just mentioned for using our Elasticsearch.
I tried searching for it in the self-hosting hide as well, but couldn't find them, Could you provide the link if it is already present?

Thank you!

**Comment by ShajithJ** [comment]
Hi @niemyjski,
Adding the query string which you mentioned, helped me resolved this problem. Thank you!

I was using the docker image created using the dockerfile in exceptionless app, On using Elasticsearch installed as a package, faced this issue.

My logs were the same "Error Loading stacks".

Meanwhile, I still face a problem on Websocket

`app.js:118801 WebSocket connection to 'wss://<url>/api/v2/push?access_token=<access-token>' failed:
`

I have created an image of the UI and used the same in the dockerfile.
On using the image provided by you, this problem didn't occur.
Could you check this one?

**Comment by niemyjski** [comment]
@ShajithJ Please open a new issue for each issue with steps to reproduce and all the relevant logs. Without either, there is not much we can do to help with very limited context to go on.

**Comment by mypublicuse** [comment]
> When this happens，exceptionless is down ，then i just delete deployment pvc（elasticsearch data） ，and reinstall deployment
> 
> k8s env。

I need help !thanks! I need the  helm with values.yaml for     exceptionless .  could you  supply to me?（ whole helm chart files）
我需要 exceptionless的完整可部署的 helmchart包（values.yaml 有示例值）,请问您能帮忙提供一份参考吗？谢谢！

**Comment by mypublicuse** [comment]
> When this happens，exceptionless is down ，then i just delete deployment pvc（elasticsearch data） ，and reinstall deployment
> 
> k8s env。
@mswinner  
I need help !thanks! I need the  helm with values.yaml for     exceptionless .  could you  supply to me?（ whole helm chart files）
我需要 exceptionless的完整可部署的 helmchart包（values.yaml 有示例值）,请问您能帮忙提供一份参考吗？谢谢！
