### ISSUE TITLE
install on k8s error !----Help

### ISSUE THREAD

**Issue by mypublicuse** [exceptionless/Exceptionless#1147]
this is two problems
1:
Error: INSTALLATION FAILED: Deployment.apps "exceptionless-elasticsearch" is invalid: spec.template.spec.initContainers[0].image: Required value

so  I edit the elasticsearch.yaml  Add
spec:
      initContainers:
        - name: sysctl
          image: mydockerhost/busybox:1.35

so  the helm can install
2:  after helm install 
i found 
 exless-nfsclient-nfs-subdir-external-provisioner-7fc86846fmlbgz   1/1     Running            0                52m
exceptionless-redis-85956947f-7vkpg                               1/1     Running            0                49m
exceptionless-app-6547d4d88d-2hkbg                                1/1     Running            0                49m
exceptionless-elasticsearch-76f6cc9b9-2jgks                       1/1     Running            0                49m
exceptionless-jobs-web-hooks-7bb9d7477c-kpmwv                     0/1     CrashLoopBackOff   14 (2m53s ago)   49m
exceptionless-jobs-event-notifications-844cb87665-bd7bt           0/1     CrashLoopBackOff   14 (2m53s ago)   49m
exceptionless-jobs-mail-message-647d6bd897-s8jmq                  0/1     CrashLoopBackOff   14 (2m55s ago)   49m
exceptionless-jobs-event-usage-75c6d6d54d-m5rjr                   0/1     CrashLoopBackOff   14 (2m46s ago)   49m
exceptionless-jobs-work-item-c74d77b55-th4g7                      0/1     CrashLoopBackOff   14 (2m34s ago)   49m
exceptionless-jobs-daily-summary-6c99dfbc87-7zq5k                 0/1     CrashLoopBackOff   14 (2m34s ago)   49m
exceptionless-jobs-event-posts-75777759b8-nsmbw                   0/1     CrashLoopBackOff   14 (2m32s ago)   49m
exceptionless-jobs-close-inactive-sessions-b49595f49-hmfxm        0/1     CrashLoopBackOff   14 (2m14s ago)   49m
exceptionless-jobs-event-user-descriptions-5c9d5dc768-8h27z       0/1     CrashLoopBackOff   14 (2m16s ago)   49m
exceptionless-jobs-stack-event-count-54ffcfb4b6-gk6mz             0/1     CrashLoopBackOff   14 (2m ago)      49m
exceptionless-jobs-maintain-indexes-27669970-s28cg                0/1     CrashLoopBackOff   5 (94s ago)      4m30s
exceptionless-collector-5c774fd8ff-6ksvx                          0/1     CrashLoopBackOff   2 (11s ago)      37s
exceptionless-api-66fc9cc659-zckzz                                0/1     CrashLoopBackOff   3 (9s ago)       55s

api  collector and jobs  is un  success!

**Comment by mypublicuse** [comment]
api:
  replicaCount: 1
  defaultDomain: api.exless.my.com
  domains: [api.exless.my.com]
  image:
    repository: mydockerhost/exceptionless/api
    tag: latest
    pullPolicy: IfNotPresent

collector:
  replicaCount: 1
  defaultDomain: cllctr.exless.my.com
  domains: [cllctr.exless.my.com]

app:
  replicaCount: 1
  defaultDomain: app.exless.my.com
  domains: [app.exless.my.com]
  image:
    repository: mydockerhost/exceptionless/ui
    tag: latest
    pullPolicy: IfNotPresent

jobs:
  image:
    repository: mydockerhost/exceptionless/job
    tag: latest
    pullPolicy: IfNotPresent
  closeInactiveSessions:
    replicaCount: 1
  dailySummary:
    replicaCount: 1
  eventNotifications:
    replicaCount: 1
  eventPosts:
    replicaCount: 1
  eventUserDescriptions:
    replicaCount: 1
  mailMessage:
    replicaCount: 1
  stackEventCount:
    replicaCount: 1
  webhooks:
    replicaCount: 1
  workitem:
    replicaCount: 1
  eventUsage:
    replicaCount: 1

statsd:
  token:
  user:

config: {}
#  key: value

service:
  type: ClusterIP

elasticsearch:
  connectionString: 
  image:
    repository: mydockerhost/exceptionless/elasticsearch
    tag: 8.3.1
    pullPolicy: IfNotPresent

redis:
  connectionString: 
  image:
    repository: mydockerhost/redis
    tag: 7.0-alpine
    pullPolicy: IfNotPresent


this  is  my values.yaml

**Comment by mypublicuse** [comment]
the log
the api and  collector pod log
 ...Back-off restarting failed container

**Comment by mypublicuse** [comment]
my [https://github.com/mypublicuse/myfile/blob/main/el-values.yaml](url)  can you help me see the problems?thanks!

**Comment by mypublicuse** [comment]
The pod  log  is 
Back-off restarting failed container   
 yes  just it!
 i guess  the program  should be  run and  immediate crash  ,so ....

**Comment by niemyjski** [comment]
It probably can't pull the image; I'd look at your pod logs / events

**Comment by ejsmith** [comment]
Crash loop back off message isn't coming from the pod logs. That is a kubernetes message and doesn't give any clues as to what is wrong. Have you tried running the all in one docker image?

**Comment by mypublicuse** [comment]
I add command command: ["/bin/bash", "-ce", "tail -f /dev/null"] to api.yaml
then  the pod log
-----------
Container exceptionless-api failed liveness probe, will be restarted
Liveness probe failed: Get "http://10.42.2.120:80/health": dial tcp 10.42.2.120:80: connect: connection refused
Started container exceptionless-api
Created container exceptionless-api
-------------------------
....

**Comment by mypublicuse** [comment]
crictl exec -it ffd274917bdc2 bash
E0812 11:04:18.083015   32528 remote_runtime.go:767] "Exec cmd from runtime service failed" err="rpc error: code = Unknown desc = container is in CONTAINER_EXITED state" containerID="ffd274917bdc2" cmd=[bash]
FATA[0000] execing command in container: rpc error: code = Unknown desc = container is in CONTAINER_EXITED state

**Comment by mypublicuse** [comment]
So I guess the program in the container started with an error, so I quit. As for why the error occurred, it seems that no useful information was found

**Comment by mypublicuse** [comment]
Let me add that I use helm install.   not  exec ex-setup.ps1 .please tell me ,Is this  problem?

**Comment by mypublicuse** [comment]
I use docker run  exceptionless/api:latest      and enter the container 
docker  exec -i testexpless  /bin/bash 
this is  when i input command   dotnet Exceptionless.Web.dll

-------
[05:09:42 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[05:09:42 WRN] Distributed cache is NOT enabled on a2991b0fd888.
[05:09:42 WRN] Distributed message bus is NOT enabled on a2991b0fd888.
[05:09:42 WRN] Distributed queue is NOT enabled on a2991b0fd888.
[05:09:42 WRN] Distributed storage is NOT enabled on a2991b0fd888.
[05:09:42 WRN] Emails will NOT be sent until the SmtpHost is configured on a2991b0fd888
[05:09:42 WRN] Using in memory file storage on a2991b0fd888
[05:09:43 ERR] Health check Elasticsearch with status Unhealthy completed after 156.3117ms with message 'null'
[05:09:43 ERR] Error running WaitForHealthChecks startup action: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Foundatio.Extensions.Hosting.Startup.StartupExtensions.<>c__DisplayClass15_0.<<AddStartupActionToWaitForHealthChecks>b__1>d.MoveNext() in /_/src/Foundatio.Extensions.Hosting/Startup/StartupExtensions.cs:line 178
--- End of stack trace from previous location ---
   at Foundatio.Extensions.Hosting.Startup.StartupActionRegistration.RunAsync(IServiceProvider serviceProvider, CancellationToken shutdownToken) in /_/src/Foundatio.Extensions.Hosting/Startup/StartupActionRegistration.cs:line 46
   at Foundatio.Extensions.Hosting.Startup.StartupExtensions.<>c__DisplayClass0_1.<<RunStartupActionsAsync>b__3>d.MoveNext() in /_/src/Foundatio.Extensions.Hosting/Startup/StartupExtensions.cs:line 50
[05:09:43 FTL] Job host terminated unexpectedly
System.IO.IOException: Failed to bind to address http://[::]:80: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Exceptionless.Web.Program.Main(String[] args) in /app/src/Exceptionless.Web/Program.cs:line 15
-------------------------------------

**Comment by mypublicuse** [comment]
when  i enter the k8s pod 
root@exceptionless-collector-b65796ccc-2vkw4:/app# curl http://localhost:80/health
curl: (7) Failed to connect to localhost port 80: Connection refused
root@exceptionless-collector-b65796ccc-2vkw4:/app# curl http://[::]:80 
curl: (7) Failed to connect to :: port 80: Connection refused
root@exceptionless-collector-b65796ccc-2vkw4:/app# curl http://[::]:80/health
curl: (7) Failed to connect to :: port 80: Connection refused
root@exceptionless-collector-b65796ccc-2vkw4:/app#

**Comment by mypublicuse** [comment]
root@exceptionless-collector-b65796ccc-2vkw4:/app# dotnet Exceptionless.Web.dll

without any display ,no logs

**Comment by mypublicuse** [comment]
uname -a
Linux exceptionless-collector-b65796ccc-2vkw4 5.4.208-1.el7.elrepo.x86_64 #1 SMP Thu Jul 28 09:02:33 EDT 2022 x86_64 GNU/Linux

my os is centos 7.9

**Comment by mypublicuse** [comment]
so  what happend  ! 

Can you give me some instructions

**Comment by mypublicuse** [comment]
oh! I got it!  is publish as Portable  ,can you  publish as linux-x64

**Comment by mypublicuse** [comment]
I entered the pod container started by k8s.

I downloaded the simple program I created (aspnet core web API)

It can work normally.

But exceptionless.web DLL does not work properly.



So I guess it must be because a dll file of the program（Exceptionless.Web） is incompatible,  But I'm not sure which  dll  it is

**Comment by niemyjski** [comment]
@mypublicuse sorry for the late followup, were you able to resolve this?

**Comment by niemyjski** [comment]
@mypublicuse sorry for the late followup, were you able to resolve this?
