### ISSUE TITLE
native es be configured?

### ISSUE THREAD

**Issue by HandsomeBoy01** [exceptionless/Exceptionless#1216]
EX_ConnectionStrings__Elasticsearch value: server=http://es-svc:9200/; username=elastic;password=ytzn9999;enable-size-plugin=false

That's right
But  still get the following error
![image](https://user-images.githubusercontent.com/40994318/212482022-ba298e72-4577-4c67-9a51-0a1180063655.png)

exceptionless/app:7.2.1 error log
[400] POST /prod-events-2023.01.11%2Cprod-events-2023.01.12%2Cprod-events-2023.01.13%2Cprod-events-2023.01.14/_search?typed_keys=true&ignore_unavailable=true

---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /prod-events-2023.01.11%2Cprod-events-2023.01.12%2Cprod-events-2023.01.13%2Cprod-events-2023.01.14/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""
--- End of inner exception stack trace ---
at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase1.CountAsync(IRepositoryQuery query, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticReadOnlyRepositoryBase.cs:line 429 at Exceptionless.Web.Controllers.EventController.GetInternalAsync(AppFilter sf, TimeInfo ti, String filter, String sort, String mode, Int32 page, Int32 limit, String after, Boolean usesPremiumFeatures) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 293 at Exceptionless.Web.Controllers.EventController.GetAsync(String filter, String sort, String time, String offset, String mode, Int32 page, Int32 limit, String after) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 205 at lambda_method648(Closure , Object ) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

# What should be the solution?

**Comment by HandsomeBoy01** [comment]
i sovled 
I add 
- name: EX_AppScope
            value:  demo # do not use prod Will report an error
