### ISSUE TITLE
MaximumRetentionDays not work in self-host environment?

### ISSUE THREAD

**Issue by gxuan0328** [exceptionless/Exceptionless#1467]
reference to #919, i understand that can setting EX_MaximumRetentionDays environment variable to regular cleanup the expired data.
but it does not work when i trun EX_RunJobsInProcess to false? 

is this a correct behavior for the origin design?

i use this(https://github.com/exceptionless/Exceptionless/blob/main/samples/docker-compose.yml) docker-compose.yml to start the exceptionless service.

**Comment by jkhcc11** [comment]
Yes, I've encountered the same issue where the settings do not take effect after configuration.

**Comment by gxuan0328** [comment]
@jkhcc11 did you also face the problem that if you use the metion docker-compose.yml to start the exceptionless aplication, then exceptionless/job will throw some error when execution the job because of elasticsearch is not already startup.
Is the job container should wait until elasticsearch is healthy, then start to execute the job? otherwise, all the one time job will failed.

`
[11:17:10 WRN] Emails will NOT be sent until the SmtpHost is configured on 468320b55a02
[11:17:10 WRN] Index Configuration is NOT enabled on 468320b55a02
[11:17:10 INF] Queue prod-WorkItemData7140309f2ce04df91c9f95 created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[11:17:10 INF] All new indexes will be created with 1 Shards and 1 Replicas
[11:17:10 INF] Starting job type Exceptionless.Core.Jobs.CleanupDataJob on machine 468320b55a02...
[11:17:10 INF] Starting job type Exceptionless.Core.Jobs.CleanupOrphanedDataJob on machine 468320b55a02...
[11:17:10 INF] Starting job type Exceptionless.Core.Jobs.Elastic.MaintainIndexesJob on machine 468320b55a02...
[11:17:10 INF] Starting index maintenance...
[11:17:10 INF] Got lock to maintain indexes
[11:17:10 ERR] Health check Elasticsearch with status Unhealthy completed after 163.0506ms with message 'null'
[11:17:10 INF] Getting duplicate stacks
[11:17:10 INF] cleanuporphaneddata job completed
[11:17:10 ERR] Failed to maintain indexes after 0:00:00.3765967: Error checking to see if alias prod-stacks
Original: [ElasticsearchClientException] The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
[] HEAD /_alias/prod-stacks

Foundatio.Repositories.Exceptions.RepositoryException: Error checking to see if alias prod-stacks
Original: [ElasticsearchClientException] The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
[] HEAD /_alias/prod-stacks

 ---> Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: Connection refused (elasticsearch:9200)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   at Elasticsearch.Net.RequestPipeline.PingAsync(Node node, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.PingAsync(IRequestPipeline pipeline, Node node, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.AliasExistsAsync(String alias) in /_/src/Foundatio.Repositories.Elasticsearch/Configuration/VersionedIndex.cs:line 95
   at Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.MaintainAsync(Boolean includeOptionalTasks) in /_/src/Foundatio.Repositories.Elasticsearch/Configuration/VersionedIndex.cs:line 155
   at Foundatio.Repositories.Elasticsearch.Jobs.MaintainIndexesJob.<>c__DisplayClass4_0.<<RunAsync>b__0>d.MoveNext() in /_/src/Foundatio.Repositories.Elasticsearch/Jobs/MaintainIndexesJob.cs:line 32
--- End of stack trace from previous location ---
   at Foundatio.Lock.LockProviderExtensions.TryUsingAsync(ILockProvider locker, String resource, Func`2 work, Nullable`1 timeUntilExpires, CancellationToken cancellationToken) in /_/src/Foundatio/Lock/ILockProvider.cs:line 53
   at Foundatio.Lock.LockProviderExtensions.TryUsingAsync(ILockProvider locker, String resource, Func`2 work, Nullable`1 timeUntilExpires, CancellationToken cancellationToken) in /_/src/Foundatio/Lock/ILockProvider.cs:line 55
   at Foundatio.Repositories.Elasticsearch.Jobs.MaintainIndexesJob.RunAsync(CancellationToken cancellationToken) in /_/src/Foundatio.Repositories.Elasticsearch/Jobs/MaintainIndexesJob.cs:line 30
[11:17:11 ERR] Job run Exceptionless.Core.Jobs.Elastic.MaintainIndexesJob failed: Error checking to see if alias prod-stacks
Original: [ElasticsearchClientException] The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
[] HEAD /_alias/prod-stacks

Foundatio.Repositories.Exceptions.RepositoryException: Error checking to see if alias prod-stacks
Original: [ElasticsearchClientException] The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
[] HEAD /_alias/prod-stacks

 ---> Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: Connection refused (elasticsearch:9200)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   at Elasticsearch.Net.RequestPipeline.PingAsync(Node node, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.PingAsync(IRequestPipeline pipeline, Node node, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.AliasExistsAsync(String alias) in /_/src/Foundatio.Repositories.Elasticsearch/Configuration/VersionedIndex.cs:line 95
   at Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.MaintainAsync(Boolean includeOptionalTasks) in /_/src/Foundatio.Repositories.Elasticsearch/Configuration/VersionedIndex.cs:line 155
   at Foundatio.Repositories.Elasticsearch.Jobs.MaintainIndexesJob.<>c__DisplayClass4_0.<<RunAsync>b__0>d.MoveNext() in /_/src/Foundatio.Repositories.Elasticsearch/Jobs/MaintainIndexesJob.cs:line 32
--- End of stack trace from previous location ---
   at Foundatio.Lock.LockProviderExtensions.TryUsingAsync(ILockProvider locker, String resource, Func`2 work, Nullable`1 timeUntilExpires, CancellationToken cancellationToken) in /_/src/Foundatio/Lock/ILockProvider.cs:line 53
   at Foundatio.Lock.LockProviderExtensions.TryUsingAsync(ILockProvider locker, String resource, Func`2 work, Nullable`1 timeUntilExpires, CancellationToken cancellationToken) in /_/src/Foundatio/Lock/ILockProvider.cs:line 55
   at Foundatio.Repositories.Elasticsearch.Jobs.MaintainIndexesJob.RunAsync(CancellationToken cancellationToken) in /_/src/Foundatio.Repositories.Elasticsearch/Jobs/MaintainIndexesJob.cs:line 30
   at Foundatio.Repositories.Elasticsearch.Jobs.MaintainIndexesJob.RunAsync(CancellationToken cancellationToken) in /_/src/Foundatio.Repositories.Elasticsearch/Jobs/MaintainIndexesJob.cs:line 44
   at Foundatio.Jobs.JobExtensions.TryRunAsync(IJob job, CancellationToken cancellationToken) in /_/src/Foundatio/Jobs/IJob.cs:line 17
[11:17:11 INF] maintainindexes job completed
[11:17:10 ERR] Job run Exceptionless.Core.Jobs.CleanupDataJob failed: Error while searching
Original: [ElasticsearchClientException] The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
[] POST /prod-organizations/_search?typed_keys=true&ignore_unavailable=true

Foundatio.Repositories.Exceptions.DocumentException: Error while searching
Original: [ElasticsearchClientException] The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
[] POST /prod-organizations/_search?typed_keys=true&ignore_unavailable=true

 ---> Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: Connection refused (elasticsearch:9200)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   at Elasticsearch.Net.RequestPipeline.PingAsync(Node node, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.PingAsync(IRequestPipeline pipeline, Node node, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Extensions.ElasticIndexExtensions.ToFindResults[T](ISearchResponse`1 response, ICommandOptions options) in /_/src/Foundatio.Repositories.Elasticsearch/Extensions/ElasticIndexExtensions.cs:line 64
   at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.FindAsAsync[TResult](IRepositoryQuery query, ICommandOptions options)
   at Exceptionless.Core.Jobs.CleanupDataJob.MarkTokensSuspended(JobContext context) in /app/src/Exceptionless.Core/Jobs/CleanupDataJob.cs:line 80
   at Exceptionless.Core.Jobs.CleanupDataJob.RunInternalAsync(JobContext context) in /app/src/Exceptionless.Core/Jobs/CleanupDataJob.cs:line 67
   at Foundatio.Jobs.JobWithLockBase.RunAsync(CancellationToken cancellationToken) in /_/src/Foundatio/Jobs/JobWithLockBase.cs:line 28
   at Foundatio.Jobs.JobWithLockBase.RunAsync(CancellationToken cancellationToken) in /_/src/Foundatio/Jobs/JobWithLockBase.cs:line 30
   at Foundatio.Jobs.JobExtensions.TryRunAsync(IJob job, CancellationToken cancellationToken) in /_/src/Foundatio/Jobs/IJob.cs:line 17
[11:17:11 INF] cleanupdata job completed
[11:17:11 ERR] Health check Elasticsearch with status Unhealthy completed after 6.8791ms with message 'null'
[11:17:12 ERR] Health check Elasticsearch with status Unhealthy completed after 2.5452ms with message 'null'
[11:17:13 ERR] Health check Elasticsearch with status Unhealthy completed after 2.8017ms with message 'null'
[11:17:14 ERR] Health check Elasticsearch with status Unhealthy completed after 2.4154ms with message 'null'
[11:17:15 INF] Waiting for startup actions to be completed for 00:05...
[11:17:15 ERR] Health check Elasticsearch with status Unhealthy completed after 21.808ms with message 'null'
[11:17:16 ERR] Health check Elasticsearch with status Unhealthy completed after 2.3286ms with message 'null'
[11:17:17 ERR] Health check Elasticsearch with status Unhealthy completed after 2.4497ms with message 'null'
[11:17:18 ERR] Health check Elasticsearch with status Unhealthy completed after 2.5654ms with message 'null'
[11:17:19 ERR] Health check Elasticsearch with status Unhealthy completed after 5.9327ms with message 'null'
[11:17:20 INF] Waiting for startup actions to be completed for 00:10...
[11:17:20 ERR] Health check Elasticsearch with status Unhealthy completed after 3.4776ms with message 'null'
[11:17:21 ERR] Health check Elasticsearch with status Unhealthy completed after 3.3933ms with message 'null'
[11:17:22 ERR] Health check Elasticsearch with status Unhealthy completed after 5.2694ms with message 'null'
[11:17:23 ERR] Health check Elasticsearch with status Unhealthy completed after 2.2268ms with message 'null'
[11:17:24 ERR] Health check Elasticsearch with status Unhealthy completed after 3.2476ms with message 'null'
[11:17:25 INF] Waiting for startup actions to be completed for 00:15...
[11:17:25 ERR] Health check Elasticsearch with status Unhealthy completed after 5.4028ms with message 'null'
[11:17:26 ERR] Health check Elasticsearch with status Unhealthy completed after 8.574ms with message 'null'
[11:17:27 ERR] Health check Elasticsearch with status Unhealthy completed after 2.7351ms with message 'null'
[11:17:28 ERR] Health check Elasticsearch with status Unhealthy completed after 1.7326ms with message 'null'
[11:17:29 ERR] Health check Elasticsearch with status Unhealthy completed after 2.637ms with message 'null'
[11:17:30 INF] Waiting for startup actions to be completed for 00:20...
[11:17:30 ERR] Health check Elasticsearch with status Unhealthy completed after 2.7926ms with message 'null'
[11:17:31 ERR] Health check Elasticsearch with status Unhealthy completed after 3.302ms with message 'null'
[11:17:32 ERR] Health check Elasticsearch with status Unhealthy completed after 2.5524ms with message 'null'
[11:17:33 ERR] Health check Elasticsearch with status Unhealthy completed after 1.924ms with message 'null'
[11:17:34 ERR] Health check Elasticsearch with status Unhealthy completed after 2.6576ms with message 'null'
[11:17:35 INF] Waiting for startup actions to be completed for 00:25...
[11:17:35 ERR] Health check Elasticsearch with status Unhealthy completed after 2.5079ms with message 'null'
[11:17:36 ERR] Health check Elasticsearch with status Unhealthy completed after 6.4453ms with message 'null'
[11:17:37 ERR] Health check Elasticsearch with status Unhealthy completed after 2.0369ms with message 'null'
[11:17:38 ERR] Health check Elasticsearch with status Unhealthy completed after 2.5949ms with message 'null'
[11:17:39 ERR] Health check Elasticsearch with status Unhealthy completed after 10.4839ms with message 'null'
[11:17:40 INF] Waiting for startup actions to be completed for 00:30...
[11:17:40 ERR] Health check Elasticsearch with status Unhealthy completed after 5.882ms with message 'null'
[11:17:41 ERR] Health check Elasticsearch with status Unhealthy completed after 2.2583ms with message 'null'
[11:17:42 ERR] Health check Elasticsearch with status Unhealthy completed after 2.0395ms with message 'null'
[11:17:43 ERR] Health check Elasticsearch with status Unhealthy completed after 2.9733ms with message 'null'
[11:17:44 ERR] Health check Elasticsearch with status Unhealthy completed after 2.1666ms with message 'null'
[11:17:45 INF] Waiting for startup actions to be completed for 00:35...
[11:17:45 ERR] Health check Elasticsearch with status Unhealthy completed after 3.0754ms with message 'null'
[11:17:46 ERR] Health check Elasticsearch with status Unhealthy completed after 4.032ms with message 'null'
[11:17:47 ERR] Health check Elasticsearch with status Unhealthy completed after 1.8216ms with message 'null'
[11:17:48 ERR] Health check Elasticsearch with status Unhealthy completed after 2.7395ms with message 'null'
[11:17:49 ERR] Health check Elasticsearch with status Unhealthy completed after 2.8935ms with message 'null'
[11:17:50 INF] Waiting for startup actions to be completed for 00:40...
[11:17:50 ERR] Health check Elasticsearch with status Unhealthy completed after 2.2849ms with message 'null'
[11:17:51 ERR] Health check Elasticsearch with status Unhealthy completed after 1.884ms with message 'null'
[11:17:52 ERR] Health check Elasticsearch with status Unhealthy completed after 3.6928ms with message 'null'
[11:17:53 ERR] Health check Elasticsearch with status Unhealthy completed after 2.3368ms with message 'null'
[11:17:54 ERR] Health check Elasticsearch with status Unhealthy completed after 3.1197ms with message 'null'
[11:17:55 INF] Waiting for startup actions to be completed for 00:45...
[11:17:56 ERR] Health check Elasticsearch with status Unhealthy completed after 3.3572ms with message 'null'
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.DownloadGeoIPDatabaseJob on machine 468320b55a02...
[11:17:58 INF] Starting job type Foundatio.Jobs.WorkItemJob on machine 468320b55a02...
[11:17:58 INF] Queue prod-MailMessage2244bfbc699bd9d376cd9b created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[11:17:58 INF] Queue prod-WebHookNotification9443abbed1e20203b9631c created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[11:17:58 INF] Starting continuous job type WorkItemJob on machine 468320b55a02...
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.MailMessageJob on machine 468320b55a02...
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.CloseInactiveSessionsJob on machine 468320b55a02...
[11:17:58 INF] Queue prod-EventNotificationeb4e3280ae1200cef7d086 created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.EventUsageJob on machine 468320b55a02...
[11:17:58 INF] Starting continuous job type EventUsageJob on machine 468320b55a02...
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.StackStatusJob on machine 468320b55a02...
[11:17:58 INF] Queue prod-EventUserDescriptionec48f29043b51a2d495563 created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.EventUserDescriptionsJob on machine 468320b55a02...
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.StackEventCountJob on machine 468320b55a02...
[11:17:58 INF] Starting job type Exceptionless.Core.Jobs.Elastic.MigrationJob on machine 468320b55a02...
[11:17:58 INF] Saving pending event usage
[11:17:58 INF] Queue prod-EventPoste8463ab5b5f1e0f9f81edf created. Retries: 1 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[11:17:58 INF] Configure MaxMindGeoIpKey to download GeoIP database.
[11:17:58 INF] downloadgeoipdatabase job completed
[11:17:59 INF] Finished saving pending event usage
[11:18:00 INF] Starting job type Exceptionless.Core.Jobs.DailySummaryJob on machine 468320b55a02...
[11:18:00 INF] Starting job type Exceptionless.Core.Jobs.WebHooksJob on machine 468320b55a02...
[11:18:00 INF] Starting job type Exceptionless.Core.Jobs.EventNotificationsJob on machine 468320b55a02...
[11:18:00 INF] Starting job type Exceptionless.Core.Jobs.EventPostsJob on machine 468320b55a02...
[11:18:00 INF] migration job completed
[11:18:00 INF] Starting continuous job type StackEventCountJob on machine 468320b55a02...
[11:18:01 INF] Starting continuous job type EventUserDescriptionsJob on machine 468320b55a02...
[11:18:02 INF] Starting continuous job type EventPostsJob on machine 468320b55a02...
[11:18:03 INF] Starting continuous job type MailMessageJob on machine 468320b55a02...
[11:18:05 INF] Starting continuous job type WebHooksJob on machine 468320b55a02...
[11:18:05 INF] Starting continuous job type EventNotificationsJob on machine 468320b55a02...
[11:18:08 INF] Starting continuous job type StackStatusJob on machine 468320b55a02...
[11:18:28 INF] Starting continuous job type CloseInactiveSessionsJob on machine 468320b55a02...
[11:18:29 INF] Saving pending event usage
[11:18:29 INF] Finished saving pending event usage
[11:18:59 INF] Saving pending event usage
[11:18:59 INF] Finished saving pending event usage
[11:19:00 INF] Starting continuous job type DailySummaryJob on machine 468320b55a02...
[11:19:00 INF] Job run DailySummaryJob succeeded: Successfully sent summary notifications.
`

**Comment by jkhcc11** [comment]
@gxuan0328  I'm sorry, I haven't resolved this issue either, as I am still on the older version. Regrettably, I end up manually deleting it every time because the logs are too large, which is quite troublesome. I am currently testing the latest version in a separate environment to verify this issue and hope to come to a conclusion.

**Comment by gxuan0328** [comment]
@jkhcc11  currently, i solved this mention cleanup issue through restart job container after all the other componet of exceptionless has successfully running. but i think it is not the best way, i still try to figure out the best practice of it.

**Comment by gxuan0328** [comment]
@jkhcc11  yes, all the outdate indices has been delete.

**Comment by niemyjski** [comment]
If you turn run jobs in process off, then you are responsible for running the cleanup jobs periodically. It looks like we should start those jobs if you don't pass any arguments to the job. Do you see logging for it on startup?

When you run in process we run it as a cron job.

        services.AddCronJob<CleanupDataJob>("30 */4 * * *");
        services.AddCronJob<CleanupOrphanedDataJob>("45 */8 * * *");
        services.AddCronJob<DownloadGeoIPDatabaseJob>("0 1 * * *");
        services.AddCronJob<MaintainIndexesJob>("10 */2 * * *");

**Comment by niemyjski** [comment]
We may need an option if you are running only one job container with everything in process to run them as a cron job. Currently they will only be cleaned up on startup which is less than ideal.

**Comment by gxuan0328** [comment]
@niemyjski  am not really sure about RunJobsInProcess this option means?

when should turn it on/off, and what situation suitable for , is there some example about it?

does that means if i turn on the RunJobsInProcess options there is no need to start a independent job container, then jobs will be register in Exceptionless.Web and run CleanupDataJob as cron job. is this correct?

**Comment by ejsmith** [comment]
https://github.com/exceptionless/Exceptionless/pull/1469
