### ISSUE TITLE
Docker and Smtp 

### ISSUE THREAD

**Issue by gianlucamasini** [exceptionless/Exceptionless#1475]
Hi everyone, I have installed the exceptionless docker image (v8.1.5 and v8.1.6) and configured the EX_ConnectionStrings__Email string, when  try to send something from the dashboard  get this error message in the logs:

Job run MailMessageJob failed: Value cannot be null. (Parameter 'text') <Exceptionless.Core.Jobs.MailMessageJob>
System.ArgumentNullException: Value cannot be null. (Parameter 'text')
   at MimeKit.Utils.ParseUtils.ValidateArguments(ParserOptions options, String text)
   at MimeKit.InternetAddressList.Parse(ParserOptions options, String text)
   at MimeKit.InternetAddressList.Parse(String text)
   at Exceptionless.Insulation.Mail.MailKitMailSender.CreateMailMessage(MailMessage notification) in /app/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs:line 100
   at Exceptionless.Insulation.Mail.MailKitMailSender.SendAsync(MailMessage model) in /app/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs:line 36
   at Exceptionless.Core.Jobs.MailMessageJob.ProcessQueueEntryAsync(QueueEntryContext`1 context) in /app/src/Exceptionless.Core/Jobs/MailMessageJob.cs:line 26

**Comment by niemyjski** [comment]
What does your connection string look like? It also looks like your SmtpFrom configuration is invalid.

**Comment by gianlucamasini** [comment]
I used sendgrid as smtp server, the configuration includes a string like this:

smtps://apikey:[realApykey]@smtp.sendgrid.net:587

**Comment by niemyjski** [comment]
Does your real api key have any special characters in it?

**Comment by gianlucamasini** [comment]
I have encoded all the special characters with the % symbol like as a query string, I have changed the configuration using another smtp server but get the same error. New smtps env string is

EX_ConnectionStrings__Email=smtps://info%40glabzone.it:T4r.......3%21%21@smtps.aruba.it:465

**Comment by gianlucamasini** [comment]
I solved it by adding the following environment variables

EX_AppMode
EX_BaseURL
EX_SmtpFrom

not present in the docker installation documentation

**Comment by niemyjski** [comment]
Would you mind updating the docs
