### ISSUE TITLE
Huge elasticsearch logs with errors and delayed logging

### ISSUE THREAD

**Issue by Kordonme** [exceptionless/Exceptionless#150]
We've experienced a LOT of elasticsearch logs (<210GB) with errors

```
[2015-09-01 00:00:22,844][DEBUG][action.bulk              ] [ex-es01] [events-v1-201508][8] failed to execute bulk item (index) index {[events-v1-201508][events][55e4ce76ba3da70e742e1672], source[{"id":"55e4ce76ba3da70e742e1672","organization_id":"55cb599aba3dab163c38f2cc","project_id":"55cb599bba3dab163c38f2cd","stack_id":"55cd8f8eba3da70e688da1c7","is_first_occurrence":false,"is_fixed":false,"is_hidden":true,"created_utc":"2015-08-31T22:00:22.8281566Z","type":"error","date":"2015-09-01T00:00:14.7002972+02:00","message":"A potentially dangerous Request.Path value was detected from the client (&).","geo":"47,6103,-122,3341", <STRIPPED DATA>]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:565)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:493)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:409)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Also, our exception logging currently seems to be delayed for about three hours. Are these two things related? When we set up Exceptionless, the logging were instant.

**Comment by niemyjski** [comment]
Hey,

I have a few questions:

* Were are these logs stored?
* What version of Elasticsearch are you using (server:9200 will tell you)?
* Are you running it on windows?
* What version of Exceptionless are you using (api/v2/status controller will tell you)?

**Comment by Kordonme** [comment]
Elasticsearch 1.7.1 is installed on Windows. The /api/v2/status page just hangs and nothing ever happens. Even after IIS restart and app pool recycle. The Exceptionless.dll, however, is version 3.1.1382.

**Comment by ejsmith** [comment]
Are you running anything to cleanup the old logs? We are using the curator tool from Elasticsearch to clean our old logs up. I think this is something we may want to put into a job though because it's not very intuitive to know that you need to run it and it would be nice if Exceptionless just handled it.

**Comment by adamzolotarev** [comment]
Could you update loggyng.yml with something like this:
  file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}.log
    **maxFileSize: 10MB**
    **maxBackupIndex: 10**
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

I haven't tried it myself. So, don't know if this would actually work.

**Comment by niemyjski** [comment]
I don't think we've ever changed the default logging.yml file. I should go check the size of our logs. Can you try this and let us know.

**Comment by niemyjski** [comment]
Yeah, we were not limiting them either but our log files are taking up like 4gb.

**Comment by adamzolotarev** [comment]
Didn't seem to break anything when I updated logging.yml. Will let you know how it goes in a few days.

**Comment by niemyjski** [comment]
Thanks! Did it cleanup any existing logs?

**Comment by adamzolotarev** [comment]
No, all existing logs are still there. I assume it should be safe to remove them manually.

**Comment by niemyjski** [comment]
Yeah, you shouldn't need them at all.

**Comment by niemyjski** [comment]
@adamzolotarev how are your changes working out?

**Comment by adamzolotarev** [comment]
Seems to be working fine. Our logs are pretty small, so haven't had a chance to verify if it will overwrite old data when it reaches the limit. But we have a single log file now instead of daily logs.

**Comment by niemyjski** [comment]
@adamzolotarev, any chance you could paste your full config here.

**Comment by adamzolotarev** [comment]
Sure:
```
# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: INFO
rootLogger: ${es.logger.level}, console, file
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN
  org.apache.http: INFO

  # gateway
  #gateway: DEBUG
  #index.gateway: DEBUG

  # peer shard recovery
  #indices.recovery: DEBUG

  # discovery
  #discovery: TRACE

  index.search.slowlog: TRACE, index_search_slow_log_file
  index.indexing.slowlog: TRACE, index_indexing_slow_log_file

additivity:
  index.search.slowlog: false
  index.indexing.slowlog: false

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}.log
    maxFileSize: 10MB
    maxBackupIndex: 10
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  # Use the following log4j-extras RollingFileAppender to enable gzip compression of log files. 
  # For more information see https://logging.apache.org/log4j/extras/apidocs/org/apache/log4j/rolling/RollingFileAppender.html
  #file:
    #type: extrasRollingFile
    #file: ${path.logs}/${cluster.name}.log
    #rollingPolicy: timeBased
    #rollingPolicy.FileNamePattern: ${path.logs}/${cluster.name}.log.%d{yyyy-MM-dd}.gz
    #layout:
      #type: pattern
      #conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  index_search_slow_log_file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}_index_search_slowlog.log
    maxFileSize: 10MB
    maxBackupIndex: 10
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  index_indexing_slow_log_file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}_index_indexing_slowlog.log
    maxFileSize: 10MB
    maxBackupIndex: 10
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

```

**Comment by niemyjski** [comment]
How has this been working out for you?

**Comment by niemyjski** [comment]
Would you mind updating the setting up elastic wiki with your findings

**Comment by adamzolotarev** [comment]
Working fine. I'll add it to wiki.

**Comment by niemyjski** [comment]
Thanks!

**Comment by niemyjski** [comment]
Just a heads up, I moved this to the elasticsearch setup guide since it's kind of related: https://github.com/exceptionless/Exceptionless/wiki/Elasticsearch-setup-guide#logging-config-optional
