### ISSUE TITLE
Implement FIPS compliant hashing

### ISSUE THREAD

**Issue by lordscarlet** [exceptionless/Exceptionless#242]
```
2016-07-29 15:01:16.6494  100 ERROR EventPostsJob Error while processing event post "q\a46c38d7f3424ee2bd19889a0c321499.json": This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms. System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA1Managed..ctor()
   at Exceptionless.Core.Extensions.HashExtensions.ToSHA1(IEnumerable`1 inputs) in C:\projects\exceptionless\Source\Core\Extensions\HashExtensions.cs:line 37
   at Exceptionless.Core.Utility.ErrorSignature.RecalculateHash() in C:\projects\exceptionless\Source\Core\Utility\ErrorSignature.cs:line 119
   at Exceptionless.Core.Utility.ErrorSignature.Parse() in C:\projects\exceptionless\Source\Core\Utility\ErrorSignature.cs:line 111
   at Exceptionless.Core.Plugins.EventProcessor.ErrorPlugin.EventProcessingAsync(EventContext context) in C:\projects\exceptionless\Source\Core\Plugins\EventProcessor\Default\20_ErrorPlugin.cs:line 37
   at Exceptionless.Core.Plugins.EventProcessor.EventProcessorPluginBase.<EventBatchProcessingAsync>d__7.MoveNext() in C:\projects\exceptionless\Source\Core\Plugins\EventProcessor\EventProcessorPluginBase.cs:line 24

```

**Comment by niemyjski** [comment]
We use this to calculate a hash of inputs to be used for stacking. Is there a way to do this in FIPS (and generate the same exact hash)? Is this supported by the .net core runtime?

**Comment by niemyjski** [comment]
https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/

**Comment by niemyjski** [comment]
@lordscarlet is there any chance you could take a look into this and see if there is a setting we could specify to ignore this error. I don't think we would be changing this code unless we can produce the same hash as it would change the stacking of every single one of events for everyone (self hosted and hosted)

**Comment by lordscarlet** [comment]
In theory we can disable it on the server, but as this is a government
machine I believe that would put is in non-compliance of standards we are
expected to follow.

**Comment by niemyjski** [comment]
You could try this in the web.config

```xml
<configuration>
   <runtime>
      <enforceFIPSPolicy enabled="0" />
   </runtime>
</configuration>
```

**Comment by niemyjski** [comment]
I'm going to close this to help keep the issues clean. If the above work arounds don't work for you please let us know. We'd also be willing to accept a pr that resolves any issues with FIPS.
