### ISSUE TITLE
Create object crash due to MD5 in Wine

### ISSUE THREAD

**Issue by kellyelton** [exceptionless/Exceptionless#28]
Not much else to say. This is linked to this wine bug http://bugs.winehq.org/show_bug.cgi?id=32194 .

I suppose my suggestion is some kind of alternative to the MD5(or .net cryptography, though I'm not sure if this affects them all).

```
 System.TypeInitializationException: The type initializer for 'Exceptionless.Utility.ObjectId' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at Microsoft.Win32.Win32Native.BCryptGetFipsAlgorithmMode(Boolean& pfEnabled)
   at System.Security.Cryptography.CryptoConfig.get_AllowOnlyFipsAlgorithms()
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct& signature, RuntimeType declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at Exceptionless.Utility.ObjectId.GetMachineHash()
   at Exceptionless.Utility.ObjectId..cctor()
   --- End of inner exception stack trace ---
   at Exceptionless.Utility.ObjectId.GenerateNewId()
   at Exceptionless.ExceptionlessClient.ToError(Exception exception, String submissionMethod, IDictionary`2 contextData)
   at Exceptionless.ExceptionlessClient.CreateError(Exception ex, Boolean isCritical, Boolean addDefaultInformation, IEnumerable`1 extendedData, IEnumerable`1 tags, String submissionMethod, IDictionary`2 contextData)
   at Exceptionless.ExceptionlessClient.ProcessUnhandledException(Exception ex, String submissionMethod, Boolean includeDefaultInformation, IDictionary`2 contextData)
   at Exceptionless.ExceptionlessManagerWpfExtensions.OnDispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.DispatcherUnhandledExceptionEventHandler.Invoke(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Octgn.OctgnApp.Main() in c:\Program Files (x86)\Jenkins\workspace\OCTGN-ReleaseTest\octgnFX\Octgn\obj\Release_Test\App.g.cs:line 0
```

**Comment by niemyjski** [comment]
I'm going to close this issue as we will be releasing 2.0 soon which features a new pcl client. None of the clients have the code that caused this error in them and as such "should" work on wine. However if you could test the 2.0 client once it's released/preview that would be greatly appreciated.
