### ISSUE TITLE
Recording log slowly 

### ISSUE THREAD

**Issue by zhouyongtao** [exceptionless/Exceptionless#329]
stable run for long time ，what needs to be configured ?
```
LOG:
2017-11-09 15:14:45.5247   11  INFO EventNotificationsJob Auto completed EventNotificationWorkItem queue entry (bd4283622184461286352e5c8518ceae). 
2017-11-09 15:14:45.5247   11  INFO EventNotificationsJob Processing EventNotificationWorkItem queue entry (dd3c6788020d4614bf6942062cf8c57c). 
2017-11-09 15:14:45.5247   22 ERROR EventPostsJob Error processing EventPost queue entry (8dbf285f430a4439a1fe3a9fb9a514e3). System.Exception: Unable to remove item from the dequeued list.
   at Foundatio.Queues.InMemoryQueue`1.<CompleteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Exceptionless.Core.Jobs.EventPostsJob.<>c__DisplayClass14_0.<<CompleteEntryAsync>b__0>d.MoveNext() in C:\projects\exceptionless\src\Exceptionless.Core\Jobs\EventPostsJob.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundatio.Utility.Async.<>c__DisplayClass3_0`1.<<Using>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundatio.Utility.Async.<Using>d__0`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Foundatio.Utility.Async.<Using>d__0`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Exceptionless.Core.Jobs.EventPostsJob.<ProcessQueueEntryAsync>d__8.MoveNext() in C:\projects\exceptionless\src\Exceptionless.Core\Jobs\EventPostsJob.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundatio.Jobs.QueueJobBase`1.<ProcessAsync>d__17.MoveNext()
2017-11-09 15:14:45.5247   22 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to remove item from the dequeued list. System.Exception: Unable to remove item from the dequeued list.
   at Foundatio.Queues.InMemoryQueue`1.<AbandonAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundatio.Jobs.QueueJobBase`1.<ProcessAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Foundatio.Jobs.QueueJobBase`1.<ProcessAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundatio.Jobs.QueueJobBase`1.<RunAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundatio.Jobs.JobExtensions.<TryRunAsync>d__0.MoveNext()`
```

**Comment by niemyjski** [comment]
What kind of behaviors are you seeing? From what I can tell you have a single node instance and you are using in memory versions. The error you are getting suggests either there was an error dequeueing an item from a concurrent queue or that there was no queue entries.  Looking at the code: https://github.com/FoundatioFx/Foundatio/blob/1c1d817d54c968484dffc536c6225fb8674b771c/src/Foundatio/Queues/InMemoryQueue.cs#L182

/I can see that it couldn't be removed or something already dequeued it. What version are you using? What happens if you restart the app (please note any enqueued items will not be processed, as the queue will be cleared)

**Comment by zhouyongtao** [comment]
this service run stable for a few months and today I found the log is slow , run one exceptionless (v4.1.0)  ,three es(v5.5) node ; when restart the exceptionless  server, i can run for a few minutes, and then log will be delayed, due to too much request ?

**Comment by niemyjski** [comment]
What is your throughput? How many events are you sending in per second? What is the resource usage on the web box?

**Comment by zhouyongtao** [comment]
I check the server throughput is not large,I think eventjob sends the request to es too slowly

**Comment by niemyjski** [comment]
Is elasticsearch on the same box as this web server? Task manager view would be better to see so we can see CPU, memory and IO

**Comment by zhouyongtao** [comment]
IIS:
![image](https://user-images.githubusercontent.com/4192762/32827515-737cd186-ca27-11e7-8bef-190de86343f5.png)
ES：
![image](https://user-images.githubusercontent.com/4192762/32827547-90adc59e-ca27-11e7-9d5b-a765242cfe7c.png)

**Comment by niemyjski** [comment]
All that looks great, what I would do is configure redis (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#redis) within the web application and then also configure an events post job but also keep the jobs running in process (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#running-jobs-out-of-process). Then you can scale out your event queue jobs to process more events. Can you try this and let us know if it's better.

**Comment by zhouyongtao** [comment]
I do this , run EventPostJob have a problem 

`2017-11-16 16:57:21.3969    1  WARN Bootstrapper StatsD Metrics is NOT enabled. 
2017-11-16 16:57:21.4281    1  WARN Bootstrapper Azure Storage is NOT enabled. 
2017-11-16 16:57:21.9437    1  INFO JobRunner Starting job type "Exceptionless.Core.Jobs.EventPostsJob" on machine "021YUN130067S"... 
2017-11-16 16:57:23.9437    4  INFO EventPostsJob Starting continuous job type "EventPostsJob" on machine "021YUN130067S"... 
2017-11-16 16:57:24.3969    5 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\d85eb62fc6494cccb5f253cc5eca2560.json'. 
2017-11-16 16:57:24.3969    6 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\5f931e842d5c4fe1a14b19a34786b3ae.json'. 
2017-11-16 16:57:24.4124    5 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\108d58e00dcb47b19c44165062569678.json'. 
2017-11-16 16:57:24.4124    7 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\a6339f7fccd048f5b209e2e6347a7e02.json'. 
2017-11-16 16:57:24.4124    4 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\6cd01fecec5545458eed4f112f9b32c8.json'. 
2017-11-16 16:57:24.4437    7 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\6bcbf92123c846abb2a731d92fb75b5a.json'. 
2017-11-16 16:57:24.7718    4 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\d55e51eff1c84f8193ae84457eb23b98.json'. 
2017-11-16 16:57:26.1781    5 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\5dc0ea4b82e042de81b0f8d5fb1db7b2.json'. 
2017-11-16 16:57:28.2563    7 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\fe4d33a50ea34f7e9f1525a0c0ee2867.json'. 
2017-11-16 16:57:29.5218    4 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\5666255340ac48ee955d90c3349c23e6.json'. 
2017-11-16 16:57:29.6000    5 ERROR EventPostsJob Job run "EventPostsJob" failed: Unable to retrieve post data info 'q\fd218c3561e74b969bc581a9ef483e9b.json'. `

**Comment by zhouyongtao** [comment]
i update exceptionless on ssd , run five events post job ,but not working better well. Initially think either network or es  server problem（es did't use ssd）.

**Comment by niemyjski** [comment]
We recommend running elastic on SSD's but depending on your throughput you should have more than enough resources as is for efficient queueing. What is your throughput? How many events are you sending in per second/hour to the exceptionless service?

**Comment by zhouyongtao** [comment]
I cleaned up the all es data，it's work , most of the data?
![image](https://user-images.githubusercontent.com/4192762/32891059-3d95f76a-cb0c-11e7-8001-bf04a546ecae.png)

**Comment by niemyjski** [comment]
Everything looks great from all the images you've sent. If you could let me know how it's acting slow. For example, I send in 10 events and it takes a minute to process them. If I have some numbers to go off of that would help.

**Comment by niemyjski** [comment]
Is this still an issue?

**Comment by niemyjski** [comment]
I'm closing this until we get more information. This all looks like adequate and I'm not sure why it would be slowing down. We are working on an asp.net core release which has much much much better performance and will really be awesome release :)

**Comment by niemyjski** [comment]
Were you able to resolve this issue and determine why it was periodically slowing down? I'm trying to remember why this issue was reopened.

**Comment by ejsmith** [comment]
This is using the inmemoryqueue and should be resolved with our latest round of Foundatio changes.

**Comment by niemyjski** [comment]
Please see the latest version 7.1.0 has these issues as we've done a bunch of perf work and bug fixes. If so please let us know and we'll reopen this issue.
