### ISSUE TITLE
Elasticsearch 6.0 is not supported

### ISSUE THREAD

**Issue by zhouyongtao** [exceptionless/Exceptionless#331]
`2017-11-15 16:27:18.5427    6 ERROR StackIndex Error creating the index stacks-v1: Original: (400 - WebException) The remote server returned an error: (400) Bad Request.
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [stacks]: [include_in_all] is not allowed for indices created on or after version 6.0.0 as [_all] is deprecated. As a replacement, you can use an [copy_to] on mapping fields to create your own catch all field." CausedBy: "Type: mapper_parsing_exception Reason: "[include_in_all] is not allowed for indices created on or after version 6.0.0 as [_all] is deprecated. As a replacement, you can use an [copy_to] on mapping fields to create your own catch all field.""
 System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.<RequestAsync>d__14`1.MoveNext()
`

**Comment by niemyjski** [comment]
This is known issue, you should be able to upgrade from 5.x to 6.x (with existing indexes) but creating indexes on 6.0 may not yet work. We have some work to do. We will be working on this in the near future (PR's welcome as well). In the mean time we **recommend staying on 5.x**.

**Comment by niemyjski** [comment]
I'm closing this as I'm merging this into #332
