### ISSUE TITLE
when i deploy with docker not work .

### ISSUE THREAD

**Issue by hongwei7458** [exceptionless/Exceptionless#413]
"exceptionless/job-ci" and "exceptionless/api-ci" not work 

error msg:
```
[tech@fr-wo-termbase1 exceptionless]$ sudo docker logs 81ee
[03:13:07 INF] Bootstrapping Exceptionless All job(s) in Production mode (5.0.3428-pre+9fad7b1694302942a57315332211d07ac66fd47a) on 81eedb32d4c8 with settings {"BaseURL": "https://be.exceptionless.io", "ConnectionStrings": {"OAuth": "FacebookId=395178683904310;GitHubId=7ef1dd5bfbc4ccf7f5ef;GoogleId=809763155066-enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com;MicrosoftId=000000004C137E8B;SlackId=34500115540.177239122322;"}, "DisableIndexConfiguration": "true", "EnableAccountCreation": "true", "ExceptionlessServerUrl": "https://collector.exceptionless.io", "InternalProjectId": "50ca6b2423d6c8493020b823"}
[03:13:07 WRN] Distributed cache is NOT enabled on 81eedb32d4c8.
[03:13:07 WRN] Distributed message bus is NOT enabled on 81eedb32d4c8.
[03:13:07 WRN] Metrics reporting is NOT enabled on 81eedb32d4c8.
[03:13:07 WRN] Distributed queue is NOT enabled on 81eedb32d4c8.
[03:13:07 WRN] Distributed storage is NOT enabled on 81eedb32d4c8.
[03:13:07 WRN] Using in memory file storage on 81eedb32d4c8
Application startup exception: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at Foundatio.Utility.ConnectionStringParser.Parse(String connectionString, IDictionary`2 synonyms)
   at Exceptionless.Core.Configuration.ConfigureElasticsearchOptions.Configure(ElasticsearchOptions options) in /app/src/Exceptionless.Core/Configuration/ElasticsearchOptions.cs:line 32
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Exceptionless.Core.Bootstrapper.LogConfiguration(IServiceProvider serviceProvider, AppOptions appOptions, ILoggerFactory loggerFactory) in /app/src/Exceptionless.Core/Bootstrapper.cs:line 243
   at Exceptionless.Job.Program.<>c__DisplayClass2_0.<CreateWebHostBuilder>b__2(IApplicationBuilder app) in /app/src/Exceptionless.Job/Program.cs:line 112
   at Microsoft.AspNetCore.Hosting.DelegateStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

here is my  YML
docker-compose.yml 

```
version: '3.4'

services:
  api:
    #depends_on:
      #- elasticsearch
    image: exceptionless/api-ci:latest
    environment:
      AppMode: Development
      ConnectionStrings__Elasticsearch: http://172.18.0.2:9200
      ConnectionStrings__Redis: redis,abortConnect=false
      RunJobsInProcess: 'false'
      StorageFolder: /app/storage
    ports:
      - 5000:80
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job-ci:latest
    command: run-all
    environment:
      AppMode: Development
      ConnectionStrings__Elasticsearch: http://172.18.0.2:9200
      ConnectionStrings__Redis: redis,abortConnect=false
      StorageFolder: /app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui-ci:latest
    environment:
      AppMode: Development
      BaseUrl: http://ex-api.localtest.me:5000
    ports:
      - 5100:80

  #elasticsearch:
   # image: slideroom/elasticsearch:98
   # environment:
   #   bootstrap.memory_lock: 'true'
   #  discovery.type: single-node
   #  ES_JAVA_OPTS: '-Xms512m -Xmx512m'
   #   xpack.security.enabled: 'false'
   #ports:
   #   - 9200:9200
   #   - 9300:9300
   # ulimits:
   #   memlock:
   #     soft: -1 
   #     hard: -1
   # volumes:
   #  - esdata:/usr/share/elasticsearch/data

  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: slideroom/kibana:116
  #   ports:
  #     - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
 
volumes:
 # esdata:
  #  driver: local
  appdata:
    driver: local
```

**Comment by niemyjski** [comment]
Hello,

You are missing a whole bunch of configuration for specifying caches and queues. Each configuration key for the connection string needs to be in `key=value;` format and needs a provider. I'm wondering if we should tweak our production configs to just use Redis and Elasticsearch out of the box so you don't have to do anything. @ejsmith do you agree with this?

In the mean time, I'd recommend taking a look at the new documentation I've been working on for docker: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting-Docker If you have any feedback on this please let me know as it would greatly help.

**Comment by niemyjski** [comment]
I need to try out your config as well, I was seeing production mode but you were specifying development.

**Comment by hongwei7458** [comment]
hi,  
thanks  for your reply,
now ,i see self-hosting-Docker 
make a suggestion :
when user deployment exceptionLess just need a docker-compose.yml file ,
the Exceptionless will be  a best project ..
looking forward to your docker-compose.yml

**Comment by niemyjski** [comment]
We have a `docker-compose` file with good defaults in the root of this repository: https://github.com/exceptionless/Exceptionless/blob/master/docker-compose.yml Can you try this out and let us know how it goes.
