### ISSUE TITLE
Type: search_phase_execution_exception Reason: "all shards failed"

### ISSUE THREAD

**Issue by yang-xiaodong** [exceptionless/Exceptionless#426]
**Elasticsearch Version:** 5.6.5
**Exceptionless Version:** master branch latest code

**Exceptionless Console error message :** 

```
[12:57:53 ERR] An error has occurred. Please check your search filter.
System.ApplicationException: Server: (400) Type: search_phase_execution_exception Reason: "all shards failed"

   at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.CountAsync(IRepositoryQuery query, ICommandOptions options)
   at Exceptionless.Web.Controllers.StackController.GetUserCountByProjectIdsAsync(ICollection`1 stacks, ExceptionlessSystemFilter sf, DateTime utcStart, DateTime utcEnd) in E:\Exceptionless\src\Exceptionless.Web\Controllers\StackController.cs:line 1048
   at Exceptionless.Web.Controllers.StackController.GetStackSummariesAsync(ICollection`1 stacks, IReadOnlyCollection`1 stackTerms, ExceptionlessSystemFilter sf, TimeInfo ti) in E:\Exceptionless\src\Exceptionless.Web\Controllers\StackController.cs:line 1017
   at Exceptionless.Web.Controllers.StackController.GetAllByTermsAsync(String aggregations, ExceptionlessSystemFilter sf, TimeInfo ti, String filter, String mode, Int32 page, Int32 limit) in E:\Exceptionless\src\Exceptionless.Web\Controllers\StackController.cs:line 973
```

**Elasticsearch logs:**

`stack_id`,  `project_id`  

Error Log :  `Fielddata is disabled on text fields by default`

```
org.elasticsearch.transport.RemoteTransportException: [I0pPAmC][192.168.2.120:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [stack_id] in order toload fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
	at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:336) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:111) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.QueryShardContext.getForField(QueryShardContext.java:166) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.resolve(ValuesSourceConfig.java:96) ~[elasticsearch-5.6.5.jar:5.6.5]
```

**Comment by yang-xiaodong** [comment]
Events mapping: 

```
{
    "state": "open",
    "settings": {
        "index": {
            "creation_date": "1558674881768",
            "number_of_shards": "1",
            "number_of_replicas": "0",
            "uuid": "xuaarFusTAWt0qmAqVFXlA",
            "version": {
                "created": "5060599"
            },
            "provided_name": "events-2019.05.24"
        }
    },
    "mappings": {
        "events": {
            "properties": {
                "date": {
                    "type": "date"
                },
                "data": {
                    "properties": {
                        "@error": {
                            "properties": {
                                "data": {
                                    "properties": {
                                        "@target": {
                                            "properties": {
                                                "ExceptionType": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                                "Message": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                                "Method": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "stack_trace": {
                                    "properties": {
                                        "module_id": {
                                            "type": "long"
                                        },
                                        "data": {
                                            "properties": {
                                                "ILOffset": {
                                                    "type": "long"
                                                }
                                            }
                                        },
                                        "file_name": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "line_number": {
                                            "type": "long"
                                        },
                                        "column": {
                                            "type": "long"
                                        },
                                        "name": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "declaring_namespace": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "parameters": {
                                            "properties": {
                                                "type_namespace": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                                "data": {
                                                    "properties": {
                                                        "IsOptional": {
                                                            "type": "boolean"
                                                        },
                                                        "IsIn": {
                                                            "type": "boolean"
                                                        },
                                                        "IsOut": {
                                                            "type": "boolean"
                                                        }
                                                    }
                                                },
                                                "name": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                                "type": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "declaring_type": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "is_signature_target": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "message": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "type": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "modules": {
                                    "properties": {
                                        "module_id": {
                                            "type": "long"
                                        },
                                        "data": {
                                            "properties": {
                                                "FileVersion": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                                "ProductVersion": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                                "PublicKeyToken": {
                                                    "type": "text",
                                                    "fields": {
                                                        "keyword": {
                                                            "ignore_above": 256,
                                                            "type": "keyword"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "name": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "is_entry": {
                                            "type": "boolean"
                                        },
                                        "created_date": {
                                            "type": "date"
                                        },
                                        "modified_date": {
                                            "type": "date"
                                        },
                                        "version": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "@submission_client": {
                            "properties": {
                                "ip_address": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "version": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "user_agent": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                }
                            }
                        },
                        "@version": {
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "ignore_above": 256,
                                    "type": "keyword"
                                }
                            }
                        },
                        "@environment": {
                            "properties": {
                                "process_id": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "data": {
                                    "properties": {
                                        "ApplicationName": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "RuntimeFramework": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "ApplicationBasePath": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "FrameworkDescription": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "ProcessArchitecture": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "ignore_above": 256,
                                                    "type": "keyword"
                                                }
                                            }
                                        }
                                    }
                                },
                                "runtime_version": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "processor_count": {
                                    "type": "long"
                                },
                                "available_physical_memory": {
                                    "type": "long"
                                },
                                "total_physical_memory": {
                                    "type": "long"
                                },
                                "ip_address": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "machine_name": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "o_s_version": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "process_memory_size": {
                                    "type": "long"
                                },
                                "thread_id": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "install_id": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "process_name": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "o_s_name": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "command_line": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "architecture": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "is_hidden": {
                    "type": "boolean"
                },
                "error": {
                    "properties": {
                        "message": {
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "ignore_above": 256,
                                    "type": "keyword"
                                }
                            }
                        },
                        "type": {
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "ignore_above": 256,
                                    "type": "keyword"
                                }
                            }
                        }
                    }
                },
                "is_fixed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "ignore_above": 256,
                            "type": "keyword"
                        }
                    }
                },
                "type": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "ignore_above": 256,
                            "type": "keyword"
                        }
                    }
                },
                "updated_utc": {
                    "type": "date"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "project_id": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "ignore_above": 256,
                            "type": "keyword"
                        }
                    }
                },
                "organization_id": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "ignore_above": 256,
                            "type": "keyword"
                        }
                    }
                },
                "stack_id": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "ignore_above": 256,
                            "type": "keyword"
                        }
                    }
                },
                "id": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "ignore_above": 256,
                            "type": "keyword"
                        }
                    }
                },
                "created_utc": {
                    "type": "date"
                },
                "is_first_occurrence": {
                    "type": "boolean"
                }
            }
        }
    },
    "aliases": [],
    "primary_terms": {
        "0": 1
    },
    "in_sync_allocations": {
        "0": [
            "gSbbx-9jTfWC9xm3Z9Ju4A"
        ]
    }
}
```

**Comment by yang-xiaodong** [comment]
I find the reason, because of redis `alias-2018.xx.xx` event cache is not deleted, so it will not create event indexs mapping again whether elasticsearch index is exists or not.

**Comment by yang-xiaodong** [comment]
Yes, we tried to upgrade Exceptionless with the latest master code. Due to some errors in this process, we suspect that the index is incompatible, so we deleted the index of events in elasticsearch, and then we encountered this error and spent for a long time to debug, because of Exceptionless dependents on Foundatio, so we did not find the reason at the first time, In the end we debugged the source code of Foundatio and found this reason.

**Comment by a14907** [comment]
> Yes, we tried to upgrade Exceptionless with the latest master code. Due to some errors in this process, we suspect that the index is incompatible, so we deleted the index of events in elasticsearch, and then we encountered this error and spent for a long time to debug, because of Exceptionless dependents on Foundatio, so we did not find the reason at the first time, In the end we debugged the source code of Foundatio and found this reason.

So if delete all events in elasticsearch, we should delete cache in redis to ensure exceptionless can rebuild the index? Which redis key should I clear to ensure the rebuild?
