### ISSUE TITLE
Issue Upgrading v3 to v4

### ISSUE THREAD

**Issue by lordscarlet** [exceptionless/Exceptionless#468]
I have been fighting with this for a while. I am trying to get our v3 instance upgraded to v4 (so I can then upgrade to v5). I believe I have everything good to go except reindexing the events. When I do so, I receive the attached error. 
[reindex error.txt](https://github.com/exceptionless/Exceptionless/files/3906348/reindex.error.txt)

My organizations are loaded, my stacks are.. maybe loaded (I can't see them without the events, I don't think). I am receiving new events when I shortly turn the v4 site on in IIS. But I get this error, and, not surprisingly, I receive no errors (even though a number of events indexes are created).

Based on having run the reindex, with errors, I am receiving no errors because of this, which I see in the logs for ElasticSearch, I assume:

```org.elasticsearch.transport.RemoteTransportException: [ex-es05][172.20.241.66:9301][indices:data/read/search[phase/query
]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [date] in order to sort on
        at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:266) ~[elasticsearch-5.0.2.jar:5.0
.2]
        at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:151) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:678) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:536) ~[elasticsearch-5.0.2.jar:5.0.2]

        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:502) ~[elasticsearch-5.0.2.jar:
5.0.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:243) ~[elasticsearch-5.0.2.jar:5.
0.2]
        at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$6(SearchTransportService
.java:276) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasti
csearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[e
lasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:550) [elasticsearch-5.0.2.jar:5.0.
2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.
java:527) [elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.2.
jar:5.0.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by niemyjski** [comment]
I'd recommend upgrading your Elasticsearch to the latest version of 5.6.x from 5.0.2 and try again, this could be the issue. Can you let me know how that goes.

**Comment by niemyjski** [comment]
Did upgrading to 5.6 resolve these issues?

**Comment by niemyjski** [comment]
Were you able to resolve this issue? Please let me know and we'll reopen this.
