### ISSUE TITLE
Relaying disallowed

### ISSUE THREAD

**Issue by mariohik** [exceptionless/Exceptionless#474]
I'm receiving the error when trying to resend email verification.
`MailKit.Net.Smtp.SmtpCommandException: Relaying disallowed as noreply@exceptionless.io
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Exceptionless.Insulation.Mail.MailKitMailSender.SendAsync(MailMessage model) in /app/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs:line 63
   at Exceptionless.Core.Jobs.MailMessageJob.ProcessQueueEntryAsync(QueueEntryContext`1 context) in /app/src/Exceptionless.Core/Jobs/MailMessageJob.cs:line 24`

Is it possible to change this email? (noreply@exceptionless.io)

**Comment by niemyjski** [comment]
Yes, You need to set an environment variable/config setting for `SmtpFrom` https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/EmailOptions.cs#L68 Please let us know if you have any questions.

**Comment by mariohik** [comment]
I am running through the docker.
Sorry, I should have said it earlier.
Are there any variables I can use in the docker-compose.yml file?

**Comment by niemyjski** [comment]
Yes, you need to set the SmtpFrom environment variable that I linked to in my previous reply
