### ISSUE TITLE
UWP Configuration

### ISSUE THREAD

**Issue by mariohik** [exceptionless/Exceptionless#566]
How can I configure an UWP application?
I'm calling ExceptionlessClient.Default.Startup on my App Initialization.
It works on DEBUG mode but when I move to RELEASE, I got an error:

`
System.PlatformNotSupportedException: Operation is not supported on this platform.
`

**Comment by niemyjski** [comment]
Are you using the latest client? What is the full stack trace?

**Comment by mariohik** [comment]
I'm using the latest vesion:
Install-Package Exceptionless -Version 4.3.2027

```csharp
public App()
{
    this.InitializeComponent();
    this.Suspending += OnSuspending;

    ExceptionlessClient.Default.Startup("<API_Key>");
}
```

Stack Trace ($exception.ToString()):
`
"System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Action´1.EndInvoke(IAsyncResult result) in f:\\dd\\ndp\\fxcore\\CoreRT\\src\\System.Private.Interop\\src\\System\\Runtime\\InteropServices\\ComAwareEventInfo.cs:line 202
   at Exceptionless.ExceptionlessConfigurationExtensions.ReadAllConfig(ExceptionlessConfiguration config, Assembly[] configAttributesAssemblies) in C:\\projects\\exceptionless-net\\src\\Exceptionless\\Extensions\\ExceptionlessConfigurationExtensions.cs:line 261
   at Exceptionless.ExceptionlessClientExtensions.Startup(ExceptionlessClient client, String apiKey) in C:\\projects\\exceptionless-net\\src\\Exceptionless\\Extensions\\ExceptionlessClientExtensions.cs:line 25
   at Fechamento.UWP.App..ctor() in C:\\Users\\mario.henrique\\source\\repos\\Fechamento\\Fechamento.UWP\\App.xaml.cs:line 39
   at Fechamento.UWP.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in C:\\Users\\mario.henrique\\source\\repos\\Fechamento\
\Fechamento.UWP\\obj\\x86\\Release\\App.g.i.cs:line 24
   at System.Func´2.Invoke(T arg)
   at __Interop.ReverseComStubs.Stub_3[TArg0](Object __this, Void* unsafe_p, IntPtr __methodPtr)"
`

**Comment by niemyjski** [comment]
Can you let me know if calling GetEntryAssembly throws this error in your app as well? https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Extensions/ExceptionlessConfigurationExtensions.cs#L259

**Comment by mariohik** [comment]
Is that right?
```csharp
public App()
{
    this.InitializeComponent();
    this.Suspending += OnSuspending;

    System.Reflection.Assembly.GetEntryAssembly();
    ExceptionlessClient.Default.Startup("<APIKey>");
}
```

If yes, call System.Reflection.Assembly.GetEntryAssembly(); run without errors.

**Comment by niemyjski** [comment]
Is there any chance you could clone the project and try attaching a project reference and running it in release mode and getting exactly where it's throwing or attach a sample uwp project here or tell me exactly the steps I need to reproduce. e.g., create a uwp app targeting xyz and then do this.
