### ISSUE TITLE
Silverlight Support

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#57]
I noticed that there are some current issues with the PCL client when using Silverlight 5. If you get the following errors this is how you get around them:

				TinyIoC.TinyIoCResolutionException occurred
	  Message=Unable to resolve type: Exceptionless.Enrichments.Default.ConfigurationDefaultsEnrichment
	  StackTrace:
		   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
	  InnerException: System.MethodAccessException
		   Message=Attempt by method 'System.Linq.Expressions.Expression.CreateLambda(System.Type, System.Linq.Expressions.Expression, System.String, Boolean, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Linq.Expressions.ParameterExpression>)' to access method 'System.Linq.Expressions.Expression`1<TinyIoC.TinyIoCContainer+ObjectConstructor>.Create(System.Linq.Expressions.Expression, System.String, Boolean, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Linq.Expressions.ParameterExpression>)' failed.
		   StackTrace:
				at System.RuntimeMethodHandle.PerformSecurityCheck(Object obj, RuntimeMethodHandleInternal method, RuntimeType parent, UInt32 invocationFlags)
				at System.RuntimeMethodHandle.PerformSecurityCheck(Object obj, IRuntimeMethodInfo method, RuntimeType parent, UInt32 invocationFlags)
				at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
				at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
				at System.Linq.Expressions.Expression.CreateLambda(Type delegateType, Expression body, String name, Boolean tailCall, ReadOnlyCollection`1 parameters)
				at System.Linq.Expressions.Expression.Lambda(Type delegateType, Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
				at System.Linq.Expressions.Expression.Lambda(Type delegateType, Expression body, ParameterExpression[] parameters)
				at TinyIoC.TinyIoCContainer.CreateObjectConstructionDelegateWithCache(ConstructorInfo constructor)
				at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
		   InnerException: 

References: https://github.com/grumpydev/TinyIoC/issues/76
To resolve this you need to run your app as elevated:

![image](https://cloud.githubusercontent.com/assets/1020579/6403547/86070440-bdd5-11e4-9553-c2fc3045a798.png)

Finally, there is an issue with the default submission client: 

		System.NotSupportedException occurred
		  Message=Specified method is not supported.
		  StackTrace:
			   at System.Net.Browser.ClientHttpWebRequest.PrepareAndSendRequest(String method, Uri requestUri, Stream requestBodyStream, WebHeaderCollection headerCollection, CookieContainer cookieContainer)
		  InnerException: 

That is thrown in the following line of code: 

        public static Task<WebResponse> GetResponseAsync(this WebRequest request) {
            return Task.Factory.FromAsync<WebResponse>(request.BeginGetResponse, request.EndGetResponse, null);
        }

I'm not sure of the fix but I did come across [this](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/e0313a7d-3808-4e55-8b49-82cb049e2833/notsupportedexception-with-httpwebrequestbegingetresponse-after-writing-to-request-stream?forum=wpdevelop)

**Comment by niemyjski** [comment]
We fixed the request Issue so now all is left is running elevated.
