### ISSUE TITLE
[Bug] An InvalidOperationException throwed while post log.

### ISSUE THREAD

**Issue by realzhaorong** [exceptionless/Exceptionless#572]
The error message as blow:

[07:16:26 ERR] HTTP POST /api/v2/events responded 500 in 25.3561 ms
[07:17:02 ERR] Error enqueuing event post.
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Foundatio.Storage.InMemoryFileStorage.ReadBytes(Stream input)
   at Foundatio.Storage.InMemoryFileStorage.SaveFileAsync(String path, Stream stream, CancellationToken cancellationToken)
   at Exceptionless.Core.Services.EventPostService.EnqueueAsync(EventPost data, Stream stream, CancellationToken cancellationToken) in /app/src/Exceptionless.Core/Services/EventPostService.cs:line 35
   at Exceptionless.Web.Controllers.EventController.PostAsync(String projectId, Int32 apiVersion, String userAgent) in /app/src/Exceptionless.Web/Controllers/EventController.cs:line 1034
[07:17:02 ERR] HTTP POST /api/v2/events responded 500 in 5.4017 ms

**Comment by niemyjski** [comment]
What version are you running? I have not ran into this and we have tests for it.

**Comment by realzhaorong** [comment]
The latest docker version from docker hub.

https://hub.docker.com/r/exceptionless/api

**Comment by niemyjski** [comment]
Can you give us the exact reproduction steps like http request made via curl (minus auth). I'm not seeing this and not seeing it in our logs either.

**Comment by niemyjski** [comment]
I fixed this in a nightly build, please use the nightly docker image that comes from this build: https://github.com/exceptionless/Exceptionless/actions/runs/82880049
