### ISSUE TITLE
Cannot create a user when self-hosting on 6.1

### ISSUE THREAD

**Issue by mariohik** [exceptionless/Exceptionless#659]
I'm running the command:
```
docker run --rm -it -p 5000:80 exceptionless/exceptionless:6.1.0
```

The application starts, but I cannot create a user:
```
[19:17:15 ERR] Error adding document
Original: [ElasticsearchClientException] Request failed to execute. Call: Status code 429 from: PUT /prod-users/_doc/5ef79b3ae8aefc0016bae19c?op_type=create&refresh=false. ServerError: Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"
Server Error (Index=null): index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];
[429] PUT /prod-users/_doc/5ef79b3ae8aefc0016bae19c?op_type=create&refresh=false

Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 429 from: PUT /prod-users/_doc/5ef79b3ae8aefc0016bae19c?op_type=create&refresh=false. ServerError: Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"
[19:17:15 FTL] Signup failed for mario@test.com: Original: (429 - ElasticsearchClientException) Request failed to execute. Call: Status code 429 from: PUT /prod-users/_doc/5ef79b3ae8aefc0016bae19c?op_type=create&refresh=false. ServerError: Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"
Server: (429) Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"

System.ApplicationException: Original: (429 - ElasticsearchClientException) Request failed to execute. Call: Status code 429 from: PUT /prod-users/_doc/5ef79b3ae8aefc0016bae19c?op_type=create&refresh=false. ServerError: Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"
Server: (429) Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"

 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 429 from: PUT /prod-users/_doc/5ef79b3ae8aefc0016bae19c?op_type=create&refresh=false. ServerError: Type: cluster_block_exception Reason: "index [prod-users-v1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];"
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(T document, ICommandOptions options)
   at Exceptionless.Web.Controllers.AuthController.SignupAsync(SignupModel model) in /app/src/Exceptionless.Web/Controllers/AuthController.cs:line 252
[19:17:15 INF] HTTP POST /api/v2/auth/signup responded 400 in 1782.6099 ms
```

**Comment by niemyjski** [comment]
We've hit this error when there is no disk space or you were over the low disk threshold. I searched on the elastic forums and this is what I came up with. https://kb.objectrocket.com/elasticsearch/how-to-fix-the-forbidden-12-read-only-api-error-in-elasticsearch-282 Please follow those steps and please let us know if you have any questions.
