### ISSUE TITLE
Exceptionless not sending emails via SMTP

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#704]
Hi, I am trying to set up SMTP to be able to get emails from Exceptionless. However, no messages are able to go through. Below are some of the variables we set, is there any relevant environment variables missing from my configuration? Or what should I look into to troubleshoot this?

```
EX_CONNECTIONSTRINGS__EMAIL: smtps://username:password@smtp.XXXX.com
EX_BASEURL: https://exceptionless.XXXX.com
EX_APIURI: https://exceptionless.XXXX.com
EX_HTML5MODE: TRUE
EX_SMTPFROM: username@XXXX.com
```

Digging through the logs, it looks like MailKit threw an error when attempting to send an email out:
```
[05:31:12 INF] Sending daily summary: users=1 project=5f233cd1e934c90298e19891
[05:31:13 INF] Queuing Exceptionless daily summary email (09/03/2020 01:00:00-09/04/2020 00:59:59) for user username@XXXX.com.
[05:31:13 INF] Done sending daily summary: users=1 project=Exceptionless events=0
[05:31:13 INF] Processing MailMessage queue entry: f4efcdc05000430f96a05c081a5853e7
[05:31:13 ERR] MailMessage queue entry f4efcdc05000430f96a05c081a5853e7 returned an unsuccessful response: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Exceptionless.Insulation.Mail.MailKitMailSender.SendAsync(MailMessage model) in /app/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs:line 46
   at Exceptionless.Core.Jobs.MailMessageJob.ProcessQueueEntryAsync(QueueEntryContext`1 context) in /app/src/Exceptionless.Core/Jobs/MailMessageJob.cs:line 24
[05:31:13 WRN] Auto abandoned MailMessage queue entry: f4efcdc05000430f96a05c081a5853e7
[05:31:13 ERR] Job run MailMessageJob failed: An error occurred while attempting to establish an SSL or TLS connection.
The host name did not match the name given in the server's SSL certificate.
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.
The host name did not match the name given in the server's SSL certificate.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Exceptionless.Insulation.Mail.MailKitMailSender.SendAsync(MailMessage model) in /app/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs:line 46
   at Exceptionless.Core.Jobs.MailMessageJob.ProcessQueueEntryAsync(QueueEntryContext`1 context) in /app/src/Exceptionless.Core/Jobs/MailMessageJob.cs:line 24
```

**Comment by Edreih** [comment]
After looking through MailKit's documenation, it looks like the issue could stem from our SSL cert, which is self-signed and not issued by a trusted CA.

Is there a way to configure this without SSL and no authentication? 
For example: `EX_CONNECTIONSTRINGS__EMAIL`: `smtp://username@smtp.XXXX.com:25`

**Comment by niemyjski** [comment]
My apologies for the late reply, I didn't even see this issue. I think that is the syntax you would use, it just needs to be a valid SmtpUri (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/EmailOptions.cs). Does that not work? It would be worth cloning and stepping through the EmailOptions class.

**Comment by niemyjski** [comment]
@Edreih Were you able to figure this out?

**Comment by Edreih** [comment]
I was able to fix this. It was an issue with our self-signed certificate, which needed to be imported as a Trusted Root CA on the server. Closing this now

**Comment by NPUlrk** [comment]
> I was able to fix this. It was an issue with our self-signed certificate, which needed to be imported as a Trusted Root CA on the server. Closing this now

I have met same errors, can you detailed solution？
