### ISSUE TITLE
docker deploy DateTimeOffset convert error

### ISSUE THREAD

**Issue by jianxuanbing** [exceptionless/Exceptionless#722]
I am deployed on docker. But, I add organization response 500.
I see the log, is a DateTime convert error.

Release: `7.0.0`
ES: `7.9.0`

```
[12:41:42 ERR] Unable to deserialize value [{"document":{"id":"5f682efcf232be0001855f0a","name":"ERP","plan_id":"EX_UNLIMITED","plan_name":"Unlimited","plan_description":"Unlimited","billing_change_date":"2020-09-21T04:41:32.7450812Z","billing_changed_by_user_id":"5f682eusage":[{"date":"2020-09-01T00:00:00Z","total":0,"blocked":0,"limit":-1,"too_big":0}],"last_event_date_utc":"0001-01-01T00:00:00","created_utc":"2020-09-21T04:41:32.7458321Z","updated_utc":"2020-09-21T04:41:32.7458321Z","is_deleted":false},"score":0.0,"id":"5f682efcf232bull]], Foundatio.Repositories, Version=7.0.0.0, Culture=neutral, PublicKeyToken=fc181f0a46f65747]]
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'last_event_date_utc', line 1, position 573.
   at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Exceptionless.Serializer.DataObjectConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /app/src/Exceptionless.Core/Serialization/DataObjectConverter.cs:line 64
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Foundatio.Serializer.JsonNetSerializer.Deserialize(Stream inputStream, Type objectType)
   at Foundatio.Serializer.SerializerExtensions.Deserialize[T](ISerializer serializer, Byte[] data)
   at Foundatio.Redis.RedisValueExtensions.ToValueOfType[T](RedisValue redisValue, ISerializer serializer)
   at Foundatio.Caching.RedisCacheClient.RedisValueToCacheValue[T](RedisValue redisValue)


```

**Comment by jianxuanbing** [comment]
my docker container set `/etc/localtime:/etc/localtime:ro` is error.
but, I remove this setting is Ok.
old version not this exception

**Comment by niemyjski** [comment]
Is there a specific reason to set that environment setting? Was this an upgraded or new organization? @ejsmith we never did a migration for last event date but that shouldn't matter.

**Comment by jianxuanbing** [comment]
This is a new environment deploy on docker. I add a new organization, then its response an error to me.

**Comment by niemyjski** [comment]
Did you create this via our ui or via http request, if you did it via http request can you send me exactly what you sent in. We've been creating new orgs over here every day without running into this. And just to confirm if you remove that from your docker config everything works

**Comment by niemyjski** [comment]
Would you mind posting your docker-config minus any sensitive info as well.

**Comment by jianxuanbing** [comment]
sorry, my server deploy on self cloud. I can send `docker-compose` to you.

**Comment by jianxuanbing** [comment]
docker image version
`exceptionless/app:7.0.0`
`exceptionless/job:7.0.0`
`exceptionless/elasticsearch:7.9.0`

**Comment by jianxuanbing** [comment]
```
version: '3.4'
services:
  app:
    image: exceptionless/app:7.0.0
    container_name: exceptionless-app
    restart: always
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://172.17.0.1:9200
      # EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      # EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=172.17.0.1:6379,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5100:80 # This can be commented out if using reverse proxy.
    volumes:
      - /data/exceptionless/data:/app/storage
      - /etc/localtime:/etc/localtime:ro

  jobs:
    depends_on:
      - app
    image: exceptionless/job:7.0.0
    container_name: exceptionless-jobs
    restart: always
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://ex-ui.localtest.me:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://172.17.0.1:9200
      # EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      # EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=172.17.0.1:6379,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - /data/exceptionless/data:/app/storage
      - /etc/localtime:/etc/localtime:ro
```

**Comment by niemyjski** [comment]
Thanks for providing this.

**Comment by niemyjski** [comment]
@Nonobis  @jianxuanbing Can you please try the latest nightly build that is going out and see if this resolves the issue if it does we'll tag it. I've been having problems reproducing it locally.

**Comment by niemyjski** [comment]
Did the latest build work for you all?

**Comment by Nonobis** [comment]
sorry i will try to test tonight.

**Comment by Nonobis** [comment]
Hello,

sorry not working.

[21:42:42 ERR] Unhandled error: Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'last_event_date_utc', line 1, position 582.

Newtonsoft.Json.JsonReaderException: Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'last_event_date_utc', line 1, position 582.
at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
at Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
at Exceptionless.Serializer.DataObjectConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /app/src/Exceptionless.Core/Serialization/DataObjectConverter.cs:line 64
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Foundatio.Serializer.JsonNetSerializer.Deserialize(Stream inputStream, Type objectType)
at Foundatio.Serializer.SerializerExtensions.Deserialize[T](ISerializer serializer, Byte[] data)
at Foundatio.Redis.RedisValueExtensions.ToValueOfType[T](RedisValue redisValue, ISerializer serializer)
at Foundatio.Caching.RedisCacheClient.RedisValueToCacheValue[T](RedisValue redisValue)
at Foundatio.Caching.RedisCacheClient.GetAllAsync[T](IEnumerable`1 keys)
at Foundatio.Caching.ScopedCacheClient.GetAllAsync[T](IEnumerable`1 keys)
at Foundatio.Caching.ScopedCacheClient.GetAllAsync[T](IEnumerable`1 keys)
at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.GetCachedFindHit(ICollection`1 ids, String cacheKey)
at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.GetByIdsAsync(Ids ids, ICommandOptions options)
at Exceptionless.Web.Controllers.ReadOnlyRepositoryApiController`3.GetModelsAsync(String[] ids, Boolean useCache) in /app/src/Exceptionless.Web/Controllers/Base/ReadOnlyRepositoryApiController.cs:line 64
at Exceptionless.Web.Controllers.OrganizationController.GetAsync(String mode) in /app/src/Exceptionless.Web/Controllers/OrganizationController.cs:line 87
at lambda_method395(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by niemyjski** [comment]
@Nonobis did you try this with a new project or organization or remove that date field from the document in elastic? I'll dig into this more regardless.

**Comment by Nonobis** [comment]
@niemyjski : Full new docker with clean redis and folder.
No residual data. I create my user, and want to create 1 organisation. => Crash

**Comment by niemyjski** [comment]
I just committed a fix for this, can you please try the nightly ci images and let me know how it works for you. I'll then tag a release.

**Comment by Nonobis** [comment]
@niemyjski : What's the tag for docker for your test version ? currenly i am using on exceptionless/exceptionless:latest
I don't see a nightly tag ?

**Comment by niemyjski** [comment]
I'm not sure if we push a -ci image for that specific image. We will tag a release shortly as I know it's working

**Comment by Nonobis** [comment]
ok no problem, i will wait. thanks for your work !

**Comment by ejsmith** [comment]
@niemyjski yes, we push all same images for CI builds. We should verify the fix before pushing an official build.

**Comment by ejsmith** [comment]
`exceptionless/exceptionless-ci:latest`

**Comment by niemyjski** [comment]
v7.0.4 has now been released https://github.com/exceptionless/Exceptionless/releases/tag/v7.0.4

**Comment by Nonobis** [comment]
@niemyjski : Working perfectly thanks you !
